// Copyright 2025 Asher Buk
// SPDX-License-Identifier: Apache-2.0
// https://github.com/AshBuk/FingerGo

/**
 * German QWERTZ keyboard layout
 * Standard German keyboard with Y/Z swapped and umlauts
 */
(() => {
    window.LAYOUT_DE_QWERTZ = {
        id: 'de-qwertz',
        name: 'Deutsch (QWERTZ)',
        language: 'de',

        rows: [
            [
                { key: '^', label: ['°', '^'] },
                { key: '1', label: ['!', '1'] },
                { key: '2', label: ['"', '2'] },
                { key: '3', label: ['§', '3'] },
                { key: '4', label: ['$', '4'] },
                { key: '5', label: ['%', '5'] },
                { key: '6', label: ['&', '6'] },
                { key: '7', label: ['/', '7'] },
                { key: '8', label: ['(', '8'] },
                { key: '9', label: [')', '9'] },
                { key: '0', label: ['=', '0'] },
                { key: 'ß', label: ['?', 'ß'] },
                { key: '´', label: ['`', '´'] },
                { key: 'Backspace', label: 'Backspace', className: 'key-wide' },
            ],
            [
                { key: 'Tab', label: 'Tab', className: 'key-wide' },
                { key: 'q', label: 'Q' },
                { key: 'w', label: 'W' },
                { key: 'e', label: 'E' },
                { key: 'r', label: 'R' },
                { key: 't', label: 'T' },
                { key: 'z', label: 'Z' },
                { key: 'u', label: 'U' },
                { key: 'i', label: 'I' },
                { key: 'o', label: 'O' },
                { key: 'p', label: 'P' },
                { key: 'ü', label: 'Ü' },
                { key: '+', label: ['*', '+'] },
                { key: '#', label: ["'", '#'], className: 'key-wide' },
            ],
            [
                { key: 'CapsLock', label: 'Caps', className: 'key-wider' },
                { key: 'a', label: 'A' },
                { key: 's', label: 'S' },
                { key: 'd', label: 'D' },
                { key: 'f', label: 'F' },
                { key: 'g', label: 'G' },
                { key: 'h', label: 'H' },
                { key: 'j', label: 'J' },
                { key: 'k', label: 'K' },
                { key: 'l', label: 'L' },
                { key: 'ö', label: 'Ö' },
                { key: 'ä', label: 'Ä' },
                { key: 'Enter', label: 'Enter', className: 'key-wider' },
            ],
            [
                { key: 'Shift', label: 'Shift', className: 'key-iso-shift' },
                { key: '<', label: ['>', '<'] },
                { key: 'y', label: 'Y' },
                { key: 'x', label: 'X' },
                { key: 'c', label: 'C' },
                { key: 'v', label: 'V' },
                { key: 'b', label: 'B' },
                { key: 'n', label: 'N' },
                { key: 'm', label: 'M' },
                { key: ',', label: [';', ','] },
                { key: '.', label: [':', '.'] },
                { key: '-', label: ['_', '-'] },
                { key: 'Shift', label: 'Shift', className: 'key-widest' },
            ],
            [{ key: ' ', label: 'Space', className: 'key-space' }],
        ],

        fingerMap: {
            // Left hand - pinky (column 1)
            '^': 'left-pinky',
            1: 'left-pinky',
            q: 'left-pinky',
            a: 'left-pinky',
            '<': 'left-pinky',
            y: 'left-pinky',
            Tab: 'left-pinky',
            CapsLock: 'left-pinky',
            // Left hand - ring (column 2)
            2: 'left-ring',
            w: 'left-ring',
            s: 'left-ring',
            x: 'left-ring',
            // Left hand - middle (column 3)
            3: 'left-middle',
            e: 'left-middle',
            d: 'left-middle',
            c: 'left-middle',
            // Left hand - index (columns 4-5)
            4: 'left-index',
            5: 'left-index',
            r: 'left-index',
            t: 'left-index',
            f: 'left-index',
            g: 'left-index',
            v: 'left-index',
            b: 'left-index',

            // Left hand - shift symbols
            '>': 'left-pinky',
            '°': 'left-pinky',
            '!': 'left-pinky',
            '"': 'left-ring',
            '§': 'left-middle',
            $: 'left-index',
            '%': 'left-index',

            // Right hand - index (columns 6-7)
            6: 'right-index',
            7: 'right-index',
            z: 'right-index',
            u: 'right-index',
            h: 'right-index',
            j: 'right-index',
            n: 'right-index',
            m: 'right-index',
            // Right hand - middle (column 8)
            8: 'right-middle',
            i: 'right-middle',
            k: 'right-middle',
            ',': 'right-middle',
            // Right hand - ring (column 9)
            9: 'right-ring',
            o: 'right-ring',
            l: 'right-ring',
            '.': 'right-ring',
            // Right hand - pinky (columns 10+)
            0: 'right-pinky',
            ß: 'right-pinky',
            '´': 'right-pinky',
            p: 'right-pinky',
            ü: 'right-pinky',
            '+': 'right-pinky',
            '#': 'right-pinky',
            ö: 'right-pinky',
            ä: 'right-pinky',
            '-': 'right-pinky',
            Backspace: 'right-pinky',
            Enter: 'right-pinky',

            // Right hand - shift symbols
            '&': 'right-index',
            '/': 'right-index',
            '(': 'right-middle',
            ')': 'right-ring',
            '=': 'right-pinky',
            '?': 'right-pinky',
            '`': 'right-pinky',
            Ü: 'right-pinky',
            '*': 'right-pinky',
            "'": 'right-pinky',
            Ö: 'right-pinky',
            Ä: 'right-pinky',
            ';': 'right-middle',
            ':': 'right-ring',
            _: 'right-pinky',

            // Thumbs
            ' ': 'thumb',
        },

        // Keys that belong to left hand (for Shift logic)
        leftHandKeys: new Set([
            '^',
            '°',
            '1',
            '!',
            '2',
            '"',
            '3',
            '§',
            '4',
            '$',
            '5',
            '%',
            'q',
            'Q',
            'w',
            'W',
            'e',
            'E',
            'r',
            'R',
            't',
            'T',
            'a',
            'A',
            's',
            'S',
            'd',
            'D',
            'f',
            'F',
            'g',
            'G',
            '<',
            '>',
            'y',
            'Y',
            'x',
            'X',
            'c',
            'C',
            'v',
            'V',
            'b',
            'B',
            'Tab',
            'CapsLock',
        ]),

        // Map shift symbols to their base keys (for keyboard highlighting)
        shiftToBaseKey: {
            '°': '^',
            '!': '1',
            '"': '2',
            '§': '3',
            $: '4',
            '%': '5',
            '&': '6',
            '/': '7',
            '(': '8',
            ')': '9',
            '=': '0',
            '?': 'ß',
            '`': '´',
            Ü: 'ü',
            '*': '+',
            "'": '#',
            Ö: 'ö',
            Ä: 'ä',
            ';': ',',
            ':': '.',
            _: '-',
            '>': '<',
        },

        // Combining mark -> dead key
        deadKeys: {
            '\u0301': '´', // acute
            '\u0300': '`', // grave
            '\u0302': '^', // circumflex
        },
    };
})();
